// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3jcdzbQSxZjJLGlGkpsn3J9qZfgh6Y_8',
    appId: '1:1027717573744:web:1adff1cbc2ec1bf8e198b5',
    messagingSenderId: '1027717573744',
    projectId: 'linkstudents8',
    authDomain: 'linkstudents8.firebaseapp.com',
    storageBucket: 'linkstudents8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDboBMRU1Ak_rVrHtI1iBSF8Nbi0hBxqqY',
    appId: '1:1027717573744:android:e1bc268e72ff4f59e198b5',
    messagingSenderId: '1027717573744',
    projectId: 'linkstudents8',
    storageBucket: 'linkstudents8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKw2936DgdH0szCdZge2ShQ59ZE4p1j18',
    appId: '1:1027717573744:ios:54efcb2f1e0dc0b4e198b5',
    messagingSenderId: '1027717573744',
    projectId: 'linkstudents8',
    storageBucket: 'linkstudents8.appspot.com',
    iosClientId: '1027717573744-iskqk5tbutqkvs73ua5qsc927q9qe5h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectwrk',
  );
}
